using CursoCSharp;
using CursoCSharp.Exercicios;

//TiposPrimitivos.ImprimirTipos();

//EntradaSaidaDados.LerArmazenar();

// ExercicioTiposPrimitivos.Exercicio// ();
// ExercicioTiposPrimitivos.Exercicio2();
// ExercicioTiposPrimitivos.Exercicio3();
// ExercicioTiposPrimitivos.Exercicio4();
// ExercicioTiposPrimitivos.Exercicio5();
// ExercicioTiposPrimitivos.Exercicio6();
// ExercicioTiposPrimitivos.Exercicio7();
// ExercicioTiposPrimitivos.Exercicio8();
// ExercicioTiposPrimitivos.Exercicio9();
// ExercicioTiposPrimitivos.Exercicio// 0();
// ExercicioTiposPrimitivos.Exercicio// // ();
// ExercicioTiposPrimitivos.Exercicio// 2();
// ExercicioTiposPrimitivos.Exercicio// 3();
// ExercicioTiposPrimitivos.Exercicio// 4();
// ExercicioTiposPrimitivos.Exercicio// 5();
// ExercicioTiposPrimitivos.Exercicio// 6();
// ExercicioTiposPrimitivos.Exercicio// 7();
// ExercicioTiposPrimitivos.Exercicio// 8();
// ExercicioTiposPrimitivos.Exercicio// 9();
// ExercicioTiposPrimitivos.Exercicio20();
// OperadoresAritmeticos.Soma();
// OperadoresAritmeticos.Divisao();
// OperadoresAritmeticos.Subtracao();
// OperadoresAritmeticos.Multiplicacao();
// OperadoresAritmeticos.Resto();
// OperadoresAritmeticos.Incremento();
// OperadoresAritmeticos.Decremento();
// ExercicioOperadoresAritmeticos.Exercicio1();
// ExercicioOperadoresAritmeticos.Exercicio2();
// ExercicioOperadoresAritmeticos.Exercicio3();
// ExercicioOperadoresAritmeticos.Exercicio4();
// ExercicioOperadoresAritmeticos.Exercicio5();
// ExercicioOperadoresAritmeticos.Exercicio6();
// ExercicioOperadoresAritmeticos.Exercicio7();
// ExercicioOperadoresAritmeticos.Exercicio8();
// ExercicioOperadoresAritmeticos.Exercicio9();
// ExercicioOperadoresAritmeticos.Exercicio10();
// ExercicioOperadoresAritmeticos.Exercicio11();
// ExercicioOperadoresAritmeticos.Exercicio12();
// ExercicioOperadoresAritmeticos.Exercicio13();
// ExercicioOperadoresAritmeticos.Exercicio14();
 ExercicioOperadoresAritmeticos.Exercicio15();
// ExercicioOperadoresAritmeticos.Exercicio16();
// ExercicioOperadoresAritmeticos.Exercicio17();
// ExercicioOperadoresAritmeticos.Exercicio18();
// ExercicioOperadoresAritmeticos.Exercicio19();
// ExercicioOperadoresAritmeticos.Exercicio20();
